language: node_js
node_js:
  - 10

before_install:
  - npm i

script:
  - npm run build

deploy:
  provider: firebase
  app: react-cloud-app
  api_key:
    secure: $FIREBASE_API_KEY
  on:
    branch: master